remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-include-cache
title: Linear Algebra & Probability
description: Documentation and Sage Cells to use for Linear Algbera & Probability
author: George Dragomir
email: george.dragomir@columbia.edu
baseurl: /lap
