remote_theme: just-the-docs
plugins:
- jekyll-seo-tag
title: Linear Algebra & Probability
description: Documentation and Sage Cells to use for Linear Algbera & Probability
author: George Dragomir
email: george.dragomir@columbia.edu
baseurl: /lap
